name: Build Safari Extension

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Convert extension for Safari
        run: |
          xcrun safari-web-extension-converter extension --project-location build --no-open
      - name: Build converted project
        run: |
          PROJ=$(find build -name '*.xcodeproj' | head -n 1)
          xcodebuild -project "$PROJ" -configuration Release CODE_SIGNING_ALLOWED=NO
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: safari-extension
          path: build
